//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BetOnPollDAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BetOnPollDALEntities : DbContext
    {
        public BetOnPollDALEntities()
            : base("name=BetOnPollDALEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_AnswerHistory> tbl_AnswerHistory { get; set; }
        public virtual DbSet<tbl_Bet> tbl_Bet { get; set; }
        public virtual DbSet<tbl_Category> tbl_Category { get; set; }
        public virtual DbSet<tbl_Poll> tbl_Poll { get; set; }
        public virtual DbSet<tbl_PollAnswer> tbl_PollAnswer { get; set; }
        public virtual DbSet<tbl_PollAnswer_Statistics> tbl_PollAnswer_Statistics { get; set; }
        public virtual DbSet<tbl_Score> tbl_Score { get; set; }
        public virtual DbSet<tbl_Statistics> tbl_Statistics { get; set; }
        public virtual DbSet<tbl_User> tbl_User { get; set; }
        public virtual DbSet<database_firewall_rules> database_firewall_rules { get; set; }
    }
}
