//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BetOnPollDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_AnswerHistory
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public int PollID { get; set; }
    
        public virtual tbl_Poll tbl_Poll { get; set; }
        public virtual tbl_User tbl_User { get; set; }
    }
}
