//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BetOnPollDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PollAnswer_Statistics
    {
        public int PollAnswerID { get; set; }
        public int StatisticsID { get; set; }
        public int Quantity { get; set; }
    
        public virtual tbl_PollAnswer tbl_PollAnswer { get; set; }
        public virtual tbl_Statistics tbl_Statistics { get; set; }
    }
}
